config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'todos#index'
  resources :todos do
    collection do
      delete :destroy_multiple
    end
    
    resources :tasks

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
validates_presence_of :name,:introduction
belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates_presence_of :name,:introduction

  has_many :tasks
  accepts_nested_attributes_for :tasks, 
  :allow_destroy => true,
  :reject_if => :all_blank, 
  :update_only => true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only:[:show,:edit,:update,:destroy]

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo =Todo.new(todo_params)
    if @todo.save
       flash[:notice] = "todo was successfully created"
       redirect_to root_path
    else
      flash[:alert] ="todo was failed to create"
      render :new
    end
  end

  def show
     @tasks = @todo.tasks.all
  end

  def edit
     
  end

  def update
    
    if @todo.update(todo_params)
      redirect_to todo_path(@todo)
      flash[:notice] = "todo was successfully updated"
    else
      render :edit
      flash[:alert] ="todo was failed to update"
    end
  end




  def destroy
    #
    @todo.destroy
    redirect_to root_path
    flash[:notice]="todo was successfully deleted"
  end


  def destroy_multiple
  Todo.destroy(params[:todo_ids]) unless params[:todo_ids].blank?

  respond_to do |format|
    format.html { redirect_to root_path }
    format.json { head :no_content }
    flash[:alert]="Departments were all successfully deleted"
  end
end
  

  private
  def set_todo
    @todo = Todo.find(params[:id])
  end

  def todo_params
    params.require(:todo).permit(:name,:introduction,tasks_attributes:[:id,:name,:introduction,:_destroy])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MultipleSelectionTodolist</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="alert alert-success alert-dismissible flash-message text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>      
        <strong><%= notice %></strong> 
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger alert-dismissible flash-message text-center" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       <strong><%= alert %></strong> 
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/todos/_form.html.erb
<style>
  .container{
    margin-top: 10px;
  }

.format{
  margin-top: 10px;
}

.label-default{
  display: inline-block;
  margin: 15px;
  padding: 5px;
}

.remove{
  color: red;
}
  
</style>

<div class="container">
  <div class="row">
    
      <%= nested_form_for(@todo) do |f| %>
         <% if @todo.errors.any? %>
            <ul>
            <% @todo.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          <% end %>






        <div class="col-md-4 format">
          <div class="form">
            <div class="form-group">
              <%= f.label :name, "部門名稱" %>
              <%= f.text_field :name,class:"form-control" %>
            </div> 

            <div class="form-group">
              <%= f.label :introduction, "相關介紹" %>
              <%= f.text_area :introduction,class:"form-control" %>
            </div> 
          </div>
        </div>
        
        <div class="clearfix"></div>

        <!--nested_form tasks-->
        <%= f.fields_for :tasks do |t| %>
          <div class="col-md-4 format">
            <div class="form">
              <div class="form-group">
                <%= t.label :name, "科系名稱" %>
                <%= t.text_field :name,class:"form-control" %>
              </div> 

              <div class="form-group">
                <%= t.label :introduction, "相關介紹" %>
                <%= t.text_area :introduction,class:"form-control" %>
              </div>     

              <%= t.link_to_remove "移除此待辦事項",class:"remove" %>

            </div>
            <hr>
          </div>
        <% end %>
        

        <%= f.link_to_add "新增相關科系", :tasks,class:"label label-default" %>

        <div class="col-md-12 text-center format">
          <%= f.submit class:"actions btn btn-default" %>
          <%= link_to "Cancel", root_path,class:"btn btn-danger" %>
        </div>
      
      <% end %>
    
  </div>
</div>

app/views/todos/edit.html.erb
<%= render partial:"form" %>

app/views/todos/index.html.erb
<div class="container">
  <div class="row">
    <h1>大學學院</h1>
    <%= form_tag destroy_multiple_todos_path, method: :delete do %>
    <%= submit_tag "刪除選中", class:"btn btn-primary" %>
    <table class="table table-striped table-bordered">

      <thead>
        <tr>
          <th>
            <input type="checkbox" onclick="toggle_checkall('todo', this.checked);" />
          </th>

          <th>Faculty</th>
          <th>Intoduction</th>
          <th>Function</th>
        </tr>
      </thead>

      <tbody>
        <% @todos.each do |todo| %>
          <tr>       
            <td><%= check_box_tag "todo_ids[]", todo.id %></td>
                         
            
            <td><%= todo.name %></td>
            <td><%= todo.introduction %></td>      
            <td>
              <%= link_to "show", todo_path(todo) %>
              <%= link_to "edit", edit_todo_path(todo) %>
              <%= link_to "delete", todo_path(todo),method: :delete ,data:{confirm:"Are You Sure ?"} %>
             </td> 


          </tr>
        <% end %> 

      </tbody>
    </table> 
    <% end %>

    <%= link_to "New Department",new_todo_path %>
  </div>
</div>



<script>
function toggle_checkall(field_name, state) {
  var checkboxes = document.getElementsByTagName('input');
  var count = checkboxes.length;
  for (var i = 0; i < count; i++) {
    if (checkboxes[i].type == "checkbox"
        && checkboxes[i].name == field_name + "_ids[]") {
      checkboxes[i].checked = state;
    }
  }
}
</script>

app/views/todos/new.html.erb
<%= render partial:"form" %>

app/views/todos/show.html.erb
<style>
  .container{
    width: 100%;
    margin: 0 auto;
    position: relative;
    transform: translateY(10%);
  }

  </style>

<div class="container">
  <div class="row">
      
      <div class="col-sm-4 col-md-3">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h3 class="panel-title text-center"><%= @todo.name %></h3>
        </div>

        <div class="panel-body">
          <p class="text-center"><strong><%= @todo.introduction %></strong></p>       
        </div>
      </div>
      </div> 
      
      <div class="clearfix"></div>

      <% @tasks.each do |task| %>
      <div class="col-sm-4 col-md-3">
      <div class="panel panel-warning">
        <div class="panel-heading">
          <h3 class="panel-title text-center"><%= task.name %></h3>
        </div>

        <div class="panel-body">
          <p class="text-center"><strong><%= task.introduction %></strong></p>       
        </div>
      </div> 
    </div>
      <% end %>


    
      <div class="col-sm-12 col-md-12">
        <%= link_to "Return",root_path,class:"btn btn-default"%>
      </div>
      
    
  </div>
</div>  